#ifndef BOOT_FAULT_H
#define BOOT_FAULT_H
#include <stdint.h>
#ifndef BOOT_ENABLE_FAULT_INJECTION
#define BOOT_ENABLE_FAULT_INJECTION 0
#endif
typedef enum {
    BOOT_FAULT_NONE, BOOT_FAULT_AFTER_PREPARING, BOOT_FAULT_DURING_ERASE,
    BOOT_FAULT_AFTER_ERASE, BOOT_FAULT_AFTER_DOWNLOAD_START,
    BOOT_FAULT_PROGRAM_10_PERCENT, BOOT_FAULT_PROGRAM_44_PERCENT,
    BOOT_FAULT_PROGRAM_90_PERCENT, BOOT_FAULT_AFTER_TRANSFER_EXIT,
    BOOT_FAULT_DURING_VERIFY, BOOT_FAULT_AFTER_VERIFY,
    BOOT_FAULT_DURING_JOURNAL_COMMIT,
    BOOT_FAULT_DURING_METADATA_COMMIT,
    BOOT_FAULT_AFTER_METADATA_PENDING,
    BOOT_FAULT_AFTER_METADATA_TRIAL,
    BOOT_FAULT_DURING_METADATA_CONFIRM,
    BOOT_FAULT_DURING_METADATA_ROLLBACK
} BootFaultPoint;
#if BOOT_ENABLE_FAULT_INJECTION
extern volatile uint32_t BootFault_ArmedPoint, BootFault_SkipHits;
void BootFault_Hit(BootFaultPoint point);
#else
static inline void BootFault_Hit(BootFaultPoint point) { (void)point; }
#endif
#endif
